version: '3.9'
services:
  sh: &base
    image: node:lts-alpine
    volumes:
      - .:/opt/code
    working_dir: /opt/code
    command: sh

  install:
    <<: *base
    command: npm install

  lint:
    <<: *base
    command: npm run lint

  test:
    <<: *base
    command: npm test

  server: &server
    <<: *base
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=postgres
    ports:
      - '8080:8080'
    depends_on:
      - db
    command: sh -c "npm install && npm run compile && bin/wait-for db:5432 -t 30 -- npm run migrate && npm start"

  watch:
    <<: *server
    command: sh -c "npm install && npm run compile && bin/wait-for db:5432 -t 30 -- npm run migrate && npm run watch"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - db
