version: '3.9'
services:
  sh: &base
    image: node:lts-alpine
    volumes:
      - .:/opt/code
    working_dir: /opt/code
    command: sh

  server:
    <<: *base
    ports:
      - '8080:8080'
    command: sh -c "npm run compile && npm start"

  watch:
    <<: *base
    ports:
      - '8080:8080'
    command: sh -c "npm run compile && npm run watch"

  install:
    <<: *base
    command: npm install

  lint:
    <<: *base
    command: npm run lint

  test:
    <<: *base
    command: npm test
