version: '3.9'
services:
  sh: &base
    image: node:lts-alpine
    volumes:
      - .:/opt/code
    working_dir: /opt/code
    command: sh

  server:
    <<: *base
    ports:
      - '3000:3000'
    command: npm run compile && node dist/server.js

  install:
    <<: *base
    command: npm install

  lint:
    <<: *base
    command: npm run lint

  test:
    <<: *base
    command: npm test
