version: '3.9'
services:
  appsh: &AppBase
    image: node:lts-alpine
    volumes:
      - ./app:/opt/code
    working_dir: /opt/code
    command: sh

  websh: &WebBase
    image: node:lts-alpine
    volumes:
      - ./web:/opt/code
    working_dir: /opt/code
    command: sh

  install:
    <<: *AppBase
    command: npm install

  lint:
    <<: *AppBase
    command: npm run lint

  test:
    <<: *AppBase
    command: npm test

  server: &server
    <<: *AppBase
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=postgres
    ports:
      - '8080:8080'
    depends_on:
      - db
    command: sh -c "npm install && npm run compile && npm run migrate && npm start"

  watch:
    <<: *server
    command: sh -c "npm install && npm run compile && npm run migrate && npm run watch"

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - db

  web:
    <<: *WebBase
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm start"
