version: '3.8'
services:
  sh: &base
    image: node:lts-alpine
    volumes:
      - .:/opt/code
    working_dir: /opt/code
    command: sh

  web:
    <<: *base
    ports:
      - '3000:3000'
    command: npm start
